all:
    g++ sndinfo.cpp -o SoundInfo
    g++ sndcat.cpp -o SoundCat
    g++ sndcvt.cpp -o SoundCvt
    g++ sndfx.cpp -o SoundFx
    g++ sndgen.cpp -o SoundGen
    g++ sndmix.cpp -o SoundMix
    g++ sndplay.cpp -o SoundPlay
clean:
    rm -f *.o SoundInfo SoundCat SoundCvt SoundFx SoundGen SoundMix SoundPlay